apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutation-webhook-example-cfg
  labels:
    app: admission-webhook-example
webhooks:
  - name: admission-service.default.svc
    objectSelector:
      matchLabels:
        run: test-admission
    clientConfig:
      service:
        name: admission-service
        namespace: default
        path: "/mutate"
        port: 8999
      caBundle: ${CA_BUNDLE}
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    admissionReviewVersions: ["v1beta1"]
    sideEffects: None